### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by MrBertie** [rcarmo/Yaki#2]
I've downloaded, run yaki/app.py, and navigated to "localhost:9090" as directed... but I just get this error message:

WebAppContext' object has no attribute 'dumbagents'
"/space" gave the following message:

```
  File "/home/symon/Downloads/yaki/snakeserver/webapp.py", line 619, in run_snakelet
    snake.serve(req, resp)          # <------ the actual call to the snakelet!
  File "/home/symon/Downloads/yaki/userlibs/yaki/Engine.py", line 294, in serve
    page = self.getPage(request, response)
  File "/home/symon/Downloads/yaki/userlibs/yaki/Engine.py", line 491, in getPage
    m = ac.dumbagents.match(request.getUserAgent())
AttributeError: 'WebAppContext' object has no attribute 'dumbagents'
```

Could you offer any suggestions?

**Comment by rcarmo** [comment]
Yeah, the main branch is missing a dumbAgents entry from the config hash in ROOT/**init**.py:

 "dumbagents" : re.compile("._(Apple-PubSub|YandexBot|GoogleBot|msnbot|bingbot|Mediapartners)._", re.IGNORECASE) # User-agents that should not be redirected to alternative URLs and get 404s

I'm doing a completely new branch now and will merge it back into master ASAP.

**Comment by MrBertie** [comment]
Thanks for the reply, I'll check in next week and try again.  As a 
fellow programmer, thanks for the hard work \o/!

**Comment by rcarmo** [comment]
You can try again today - I just pushed the whole shebang out to the master branch.

Not much in the way of docs yet, but you can always add new pages with your questions to the docs folder and send me a pull request :)
